version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    ignored_updates:
      - match:
          # Slow Build: https://github.com/spotify/dockerfile-maven/issues/329
          dependency_name: "com.spotify:dockerfile-maven-plugin"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
