server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: tag-service
  kafka:
    bootstrap-servers: redpanda:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: gzip
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: project-service
    properties:
      "spring.json.trusted.packages": "*"
      "spring.deserializer.value.delegate.class": org.apache.kafka.common.serialization.StringDeserializer
      "spring.deserializer.key.delegate.class": org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    password: tag-service
    url: jdbc:postgresql://tag-db:5432/tag-db
    username: tag-service
    hikari:
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.aws.innovation-hub.de/auth/realms/innovation-hub-bergisches-rheinland
logging:
  level:
    de.innovationhub.prox.tagservice: DEBUG
