keycloak:
  auth-server-url: https://login.aws.innovation-hub.de/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  realm: innovation-hub-bergisches-rheinland
  resource: prox-tag-service
server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: tag-service
  data:
    rest:
      max-page-size: 1000000000
      default-page-size: 1000000000
  kafka:
    bootstrap-servers: redpanda:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
      properties:
        "schema.registry.url": http://redpanda-cluster:8081
  datasource:
    password: tag-service
    url: jdbc:postgresql://tag-db:5432/tag-db
    username: tag-service
    hikari:
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
