server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: tag-service
  kafka:
    bootstrap-servers: redpanda:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      group-id: tag-service
    properties:
      "schema.registry.url": http://redpanda-cluster:8081
  datasource:
    password: tag-service
    url: jdbc:postgresql://tag-db:5432/tag-db
    username: tag-service
    hikari:
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.aws.innovation-hub.de/auth/realms/innovation-hub-bergisches-rheinland
logging:
  level:
    de.innovationhub.prox.tagservice: DEBUG
