node {
    def changelist = "gp-ws2019-${env.BUILD_NUMBER}"

    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        docker.image('maven:3.6.1-jdk-8-alpine').inside {
            writeFile file: 'settings.xml', text: "<settings><localRepository>${pwd()}/.m2</localRepository></settings>"

            withCredentials([usernamePassword(credentialsId: 'archilab-nexus-jenkins', usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD')]) {
                sh "mvn -B -s settings.xml -Ddockerfile.username=\"$NEXUS_USERNAME\" -Ddockerfile.password=\"$NEXUS_PASSWORD\" -Dchangelist=${changelist} clean deploy"
            }
        }
    }

    stage('Deploy') {
        docker.withServer('tcp://10.10.10.43:2376', 'prox-gp-ws2019-certs') {
            def pom = readMavenPom file: 'pom.xml'
            def image = pom.getArtifactId()
            def revision = pom.getProperties().getProperty('revision')
            def tag = "${revision}-${changelist}"

            docker.withRegistry('https://docker.nexus.archi-lab.io', 'archilab-nexus-jenkins') {
                sh "env IMAGE=${image} TAG=${tag} docker stack deploy --with-registry-auth -c src/main/docker/docker-compose.yml ${image}"
            }
        }
    }
}
