version: "3.7"

services:

  tag-db:
    image: postgres:11.3-alpine
    environment:
      - POSTGRES_USER=tags-service
      - POSTGRES_PASSWORD=tags-service
      - POSTGRES_DB=tags-db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

